spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/android_shop
    username: root
    password: 1234

mybatis-plus:
  type-aliases-package: com.example.canteen_review.entity.po, com.example.canteen_review.entity.vo
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
